# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
      args:
        COMET_API_KEY: ${COMET_API_KEY}
    image: ift6758/serving:0.0.1
    ports:
        8890:8890
    environment:
        COMET_API_KEY=$COMET_API_KEY
#### Uncomment below when you're ready to add the final notebook container to your docker compose
  streamlit:
    build:
     context: ./
     dockerfile: ./Dockerfile.streamlit
      args:
        COMET_API_KEY: ${COMET_API_KEY}
    image: ift6758/streamlit:0.0.2
    ports:
       8890:8890
    environment:
      COMET_API_KEY=$COMET_API_KEY
      

     
