# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    image: ift6758/serving:0.0.1
    env_file:
      - .env
    volumes:
      - ./flask.log:/code/flask.log
    expose:
      - 5000
    ports:
      - 5000:5000
    environment:
      COMET_API_KEY: ${COMET_API_KEY}

  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
      #args:
      #  COMET_API_KEY: ${COMET_API_KEY}
    image: ift6758/streamlit:0.0.2
    env_file:
      - .env
    expose:
      - 8501
    ports:
      - 8501:8501
    environment:
      COMET_API_KEY: ${COMET_API_KEY}

